refactor(member): 활동 QA 피드백 반영 수정
kgu-clab/clab-platforms pull request #221
Opened 2024-08-25 15:10 UTC by Jeong-Ag

## Summary

#220 

운영진 대상으로 진행된 활동 QA의 피드백을 반영하여 코드를 수정합니다.

## Tasks

- 주차별 활동 추가 후 input 초기화
- Textarea 제한 글자 수 초과 시 API 요청 막기
-  활동 그룹 프로필 편집 후 활동 페이지 메인에 변경 내역 반영되도록 수정
- 활동 멤버 관리 버튼명 수정
- 활동 멤버 레벨 변경 기능 추가
-  API 중복 요청 막기
-  활동 신청 후 활동 메인 페이지로 이동
- KST로 시간 변환
- 첨부 파일 조회 불가 에러 수정
- 반응형 조정
- 자신이 참여중인 활동과 지원한 그룹 확인 추가
- 활동 그룹 중복 지원 시 안내 Toast 추가
- header 클릭 시 해당 페이지로 이동
- 과제 수정 플로우 변경

## ETC

- 2차 QA 진행 예정입니다.

## Screenshot

<img width="1792" alt="스크린샷 2024-08-25 오후 7 12 34" src="https://github.com/user-attachments/assets/23939a2b-d9df-4768-a52f-55b0d06b4962">
<img width="1792" alt="스크린샷 2024-08-25 오후 7 12 46" src="https://github.com/user-attachments/assets/9252c998-4a54-40f8-8564-7ec6245b6fec">
<img width="1792" alt="스크린샷 2024-08-25 오후 7 12 57" src="https://github.com/user-attachments/assets/01792c68-b4d0-4650-9f40-7293818defc0">
<img width="1792" alt="스크린샷 2024-08-25 오후 7 12 54" src="https://github.com/user-attachments/assets/ac85ba6a-66b6-4e90-b3f2-50909ba95fb8">

2024-08-25 15:40 UTC, SWARVY requested changes
수고하셨어요. 아래 리뷰사항 읽어보시고 의견 있으시면 나눠봐요 :)

2024-08-25 15:40 UTC, SWARVY commented on apps/member/src/components/group/ActivityAssignmentEditor/ActivityAssignmentEditor.tsx
> +    await setBoard(defaultBoard);
`setBoard`까지 `await` 해줘야할 이유가 있을까요?
`activityGroupBoardMutate` 완료 이후 실행되는 로직이니 해당 `await` 문은 불필요해보입니다.

```suggestion
    setBoard(defaultBoard);
```

2024-08-25 15:40 UTC, SWARVY commented on apps/member/src/components/group/ActivityPostEditor/ActivityPostEditor.tsx
>      Array.from({ length: activities.length }, () => false),
이전에 말씀드렸던 `Array.from`을 잘 사용하고계시네요, 좋습니다 👍🏻

2024-08-25 15:40 UTC, SWARVY commented on apps/member/src/components/group/AssignmentUploadSection/AssignmentUploadSection.tsx
> +              disabled={!editMode && !(myAssignment === undefined)} // 제출물이 없는 상태엔 입력 가능, 제출물이 있지만 수정하기 버튼이 클릭되지 않으면 수정 불가
반드시 `undefined`인 경우만 걸러내야하나요?
부정형의 값이 모두 안되는거라면 `!myAssignment`가 조금 더 깔끔해보이지 않을까 싶어요

2024-08-25 15:40 UTC, SWARVY commented on apps/member/src/components/group/AssignmentUploadSection/AssignmentUploadSection.tsx
> +        {uploadedFile !== null && !editMode && (
해당 경우도 아래처럼 작성하는게 더 깔끔해보일거같아요

```suggestion
        {uploadedFile && !editMode && (
```

2024-08-25 15:40 UTC, SWARVY commented on apps/member/src/constants/message.ts
> +  ALREADYAPPLIEDEXCEPTION: '이미 신청한 활동이에요.',
메시지를 하이픈으로 구분해주는 건 어떨까요? 지금 상수는 너무 읽기 어려운 것 같아요

```suggestion
  BOOK_ALREADY_BORROWED_EXCEPTION: '해당 도서는 대여 상태에요.',
  OVER_DUE_EXCEPTION: '도서 대여 연장은 최대 2회까지 가능해요.',
  NOT_FOUND_EXCEPTION: '요청하신 정보를 찾을 수 없어요.',
  ALREADY_APPLIED_EXCEPTION: '이미 신청한 활동이에요.',
```

2024-08-25 15:40 UTC, SWARVY commented on apps/member/src/hooks/queries/activity/useActivityGroupMemberMutation.ts
>    const mutation = useMutation({
`mutation` 불러와서 사용하는게 `mutate`, `isPending` 두가지라면, 간단하게 위에서 정리해보는것도 좋아보입니다.
꼭 아래와 같이 할 필요는 없어용

```suggestion
  const { mutate: activityGroupMemberMutate, isPending: activityGroupMemberIsPending } = useMutation({
```
<br/>
위처럼 작성하면 아래에서 그냥 간단하게 `return` 해줄 수 있겠네요

```ts
  return { activityGroupMemberMutate, activityGroupMemberIsPending };
```

2024-08-25 15:40 UTC, SWARVY commented on apps/member/src/pages/GroupPage/GroupPage.tsx
> +  });
`data`들에 대해서 구분을 해 주고 있다면 `refetch`도 어떤 데이터와 관련된 것인지 명확하게 나타내보는건 어떨까요?

```suggestion
  const { data: progressingData } = useActivityGroupMember();
  const { data: waitingData } = useActivityGroupMemberApplied();
  const { refetch: acceptedDataRefetch, data: acceptedData } = useMyActivityGroupMember({
    status: subMenu.value,
  });
```

2024-08-25 15:40 UTC, SWARVY commented on apps/member/src/pages/GroupPage/GroupPage.tsx
> +  }, [subMenu]);
`deps` 빠진 부분 추가해주시면 될 것 같아요

그리고 왠지 모르겠는데, 공용 레포에서 `deps` 빠진거 린팅이 안들어가는 것 같은데, 저만 그런가요?
@gwansikk @Jeong-Ag

2024-08-25 15:42 UTC, gwansikk commented on apps/member/src/components/group/ActivityAssignmentEditor/ActivityAssignmentEditor.tsx
> +    await setBoard(defaultBoard);
추가로 `mutate`에서 `onSuccess`를 사용하여 사이트 이펙트를 핸들링하면 좋을 거 같아요.

2024-08-25 23:42 UTC, gwansikk requested changes

2024-08-25 23:42 UTC, gwansikk commented on apps/member/src/components/common/Textarea/Textarea.tsx
> +  ({ id, label, className, value, maxLength, disabled, ...rest }, ref) => {
```suggestion
  ({ id, label, className, value, maxLength, disabled, ...props }, ref) => {
```

2024-08-25 23:42 UTC, gwansikk commented on apps/member/src/components/group/ActivityConfigTableSection/ActivityConfigTableSection.tsx
> +              {formattedDate(toKoreaISOString(board.updatedAt || ''))}
```suggestion
              {formattedDate(toKoreaISOString(board.updatedAt ?? ''))}
```
```suggestion
              {formattedDate(toKoreaISOString(board.updatedAt))}
```

`toKoreaISOString` 내부에서 예외처리를 하는 건 어떨까요??

2024-08-25 23:42 UTC, gwansikk commented on apps/member/src/components/group/ActivityNoticeEditor/ActivityNoticeEditor.tsx
> +    await setNotice(defaultNotice);
Mutate의 `onSuccess`를 사용하여 사이트 이펙트를 관리할 수 있어요

2024-08-25 23:42 UTC, gwansikk commented on apps/member/src/constants/message.ts
> +  ALREADYAPPLIEDEXCEPTION: '이미 신청한 활동이에요.',
> 메시지를 하이픈으로 구분해주는 건 어떨까요? 지금 상수는 너무 읽기 어려운 것 같아요
> 
> 
> 
> ```suggestion
> 
>   ALREADY_BORROWED_BOOK_EXCEPTION: '해당 도서는 대여 상태에요.',
> 
>   OVER_DUE_EXCEPTION: '도서 대여 연장은 최대 2회까지 가능해요.',
> 
>   NOT_FOUND_EXCEPTION: '요청하신 정보를 찾을 수 없어요.',
> 
>   ALREADY_APPLIED_EXCEPTION: '이미 신청한 활동이에요.',
> 
> ```

해당 에러코드는 서버팀과 논의 후에 결정하게 됐어요, 해당 키가 동일하게 서버에서 리턴하여 에러 메시지와 맵핑되는 형식이에요

2024-08-25 23:42 UTC, gwansikk commented on apps/member/src/hooks/queries/activity/useActivityGroupMemberRoleMutation.ts
> +          message: '멤버 레벨 변경에 실패했어요.',
```suggestion
          message: '멤버 권한 변경에 실패했어요.',
```

2024-08-26 04:43 UTC, gwansikk commented on apps/member/src/constants/message.ts
> +  ALREADYAPPLIEDEXCEPTION: '이미 신청한 활동이에요.',
@mingmingmon @limehee 에러 처리 부분 개선 가능한지 확인 부탁드려요~

2024-08-26 05:02 UTC, limehee commented on apps/member/src/constants/message.ts
> +  ALREADYAPPLIEDEXCEPTION: '이미 신청한 활동이에요.',
서버에서 던지는 예외를 사용자가 이해하기 어렵게 만들려는 취지에서 @gwansikk 님과 논의한 끝에 현재의 형태로 전달하게 되었어요. 서버 코드베이스에서는 예외명이 명확하게 보여 작업에 지장을 주지 않지만, 말씀해주신 것처럼 응답을 확인할 때는 이해하기 어려워 프론트엔드 입장에서 상수화하더라도 오탈자 확인이 어려워질 수 있고, 나중에 합류하는 팀원이 이 부분을 이해하는 데 어려움을 느낄 수 있다는 생각이 듭니다. 현재 서버가 Public으로 관리되고 있고, 사용자가 예외를 안다고 해서 심각한 문제가 발생할 가능성은 낮다고 판단돼요. 따라서, 프로젝트의 유지보수성과 가독성을 위해 `_`를 붙이는 방법에도 동의합니다.

다만, 가독성 문제만을 고려한다면, 서버에서 예외명을 대문자로 변환하지 않고 카멜케이스로 반환하는 방법도 고려해볼 수 있을 것 같아요. 지금처럼 `_`를 붙이는 방식은 백엔드에서 던지는 예외를 프론트엔드에서 캐치할 때 예외명을 잘못 설정하는 오류가 발생할 수 있어, 이 부분에 대한 보완이 필요할 것 같습니다.

2024-08-26 05:49 UTC, gwansikk commented on apps/member/src/pages/GroupPage/GroupPage.tsx
> +  }, [subMenu]);
> `deps` 빠진 부분 추가해주시면 될 것 같아요
> 
> 
> 
> 그리고 왠지 모르겠는데, 이 레포에서 `deps` 빠진거 린팅이 안들어가는 것 같은데, 저만 그런가요?
> 
> @gwansikk @Jeong-Ag 

의도한 부분일 수도 있겠다는 생각에 저는 코드리뷰를 제외했어요

2024-08-30 09:34 UTC, Jeong-Ag commented on apps/member/src/components/group/ActivityAssignmentEditor/ActivityAssignmentEditor.tsx
> +    await setBoard(defaultBoard);
[974f843](https://github.com/kgu-clab/clab-platforms/pull/221/commits/974f8434fb4096f0d43176c1d3adec564d536dff) 해당 부분 동의하여 수정하였습니다!

2024-08-30 09:36 UTC, Jeong-Ag commented on apps/member/src/components/group/AssignmentUploadSection/AssignmentUploadSection.tsx
> +              disabled={!editMode && !(myAssignment === undefined)} // 제출물이 없는 상태엔 입력 가능, 제출물이 있지만 수정하기 버튼이 클릭되지 않으면 수정 불가
[a60b46e](https://github.com/kgu-clab/clab-platforms/pull/221/commits/a60b46e0168d20b3baa4e3c4f8ecab9a06656758) boolean 값으로 처리되어야 해서 위와 같은 방법을 사용하였는데 타입 변환하는 것으로 수정하였습니다~

2024-08-30 09:37 UTC, Jeong-Ag commented on apps/member/src/constants/message.ts
> +  ALREADYAPPLIEDEXCEPTION: '이미 신청한 활동이에요.',
[989a5c1](https://github.com/kgu-clab/clab-platforms/pull/221/commits/989a5c1d215f150e195c0b1b79694b34637ad656) 아래 @gwansikk 님이 남겨주신 수정된 에러코드로 개선했어요 :)

2024-08-30 09:38 UTC, Jeong-Ag commented on apps/member/src/hooks/queries/activity/useActivityGroupMemberMutation.ts
>    const mutation = useMutation({
[974f843](https://github.com/kgu-clab/clab-platforms/pull/221/commits/974f8434fb4096f0d43176c1d3adec564d536dff) 더 알아보기 쉬운 방법인 것 같아서 수정하였습니다! 감사해요

2024-08-30 09:41 UTC, Jeong-Ag commented on apps/member/src/pages/GroupPage/GroupPage.tsx
> +  }, [subMenu]);
[974f843](https://github.com/kgu-clab/clab-platforms/pull/221/commits/974f8434fb4096f0d43176c1d3adec564d536dff) `deps`에 들어가지 않아도 문제 없다고 판단하여서 추가하지 않았는데 린팅에 나오네요. 추가하는 게 좋을 것 같아요

2024-08-30 09:43 UTC, Jeong-Ag commented on apps/member/src/components/group/ActivityNoticeEditor/ActivityNoticeEditor.tsx
> +    await setNotice(defaultNotice);
[974f843](https://github.com/kgu-clab/clab-platforms/pull/221/commits/974f8434fb4096f0d43176c1d3adec564d536dff) 오 좋은 방법 제안주셔서 감사합니다! 해당 내용으로 리팩토링 진행하였어요

2024-08-30 09:43 UTC, Jeong-Ag commented on apps/member/src/hooks/queries/activity/useActivityGroupMemberRoleMutation.ts
> +          message: '멤버 레벨 변경에 실패했어요.',
[989a5c1](https://github.com/kgu-clab/clab-platforms/pull/221/commits/989a5c1d215f150e195c0b1b79694b34637ad656) 변경된 에러코드로 수정하였어요

2024-08-30 10:45 UTC, gwansikk requested changes

2024-08-30 10:45 UTC, gwansikk commented on apps/member/src/components/group/ActivityNoticeEditor/ActivityNoticeEditor.tsx
> +    if (activityGroupBoardIsSuccess) setNotice(defaultNotice);
`mutate`의 `onSuccess`를 사용하면 사이드 이펙트를 순서를 보장하여 핸들링 할 수 있어요

2024-08-30 10:45 UTC, gwansikk commented on apps/member/src/components/group/GroupCreateSection/GroupCreateSection.tsx
> +            placeholder="https://github.com/KGU-C-Lab"
오가니제이션 이름이 변경됐어요 `kgu-clab`

2024-08-30 11:05 UTC, Jeong-Ag commented on apps/member/src/components/group/ActivityNoticeEditor/ActivityNoticeEditor.tsx
> +    if (activityGroupBoardIsSuccess) setNotice(defaultNotice);
await와 isSuccess 사용 대신 제시해주신 방법으로 리팩토링 했습니다!

2024-08-30 11:38 UTC, mingmingmon commented on apps/member/src/constants/message.ts
> +  ALREADYAPPLIEDEXCEPTION: '이미 신청한 활동이에요.',
저도 `_`를 붙이거나 카멜케이스로 수정하는 방식에 동의합니다. 가독성을 위해서라면 개인적으로는 `_` 방식이 더 읽기 좋은데, 프론트분들이 선호하시는 방식 알려주세요!

2024-08-31 04:36 UTC, gwansikk commented on apps/member/src/constants/message.ts
> +  ALREADYAPPLIEDEXCEPTION: '이미 신청한 활동이에요.',
해당 부분은 일단 _ 없이 기존 방법으로 하는게 좋을 거 같아요. 기존 방식으로 사용하는 부분도 많고 변경점이 많아 추후 추가로 이슈를 만들어 적용하는 것으로 해요. 관련해서 변경해야할 시기가 되면 알려드릴게요.

@Jeong-Ag @SWARVY @limehee @mingmingmon

2024-08-31 04:39 UTC, gwansikk approved these changes
LGTM

2024-08-31 04:58 UTC, Jeong-Ag commented on apps/member/src/constants/message.ts
> +  ALREADYAPPLIEDEXCEPTION: '이미 신청한 활동이에요.',
네 확인했습니다~

2024-08-31 12:41 UTC, SWARVY approved these changes
수고하셨습니다. 어프롭할게요~

2024-08-31 12:42 UTC, merged