feat: 타임테이블 시각화
kgu-clab/clab-platforms pull request #223
Opened 2024-08-29 08:51 UTC by SWARVY

## Summary

> #214 

선택한 강의를 화면에 시각화합니다

## Tasks

- 시간표 목록에서 시간표를 선택하고, 이를 타임테이블에 반영할 수 있습니다.
- 목록에서 선택시 타임테이블에 강의가 반영되고, 선택된 영역을 클릭하여 해당 데이터를 삭제할 수 있습니다.
- `export / import`경로를 조정했습니다. `widgets` 루트에 존재하던 `index.ts`를 삭제하여 `import types`로 관리되는 영역을 조금 더 명확하게 구분하고, 해당 데이터의 역할이 무엇인지 조금 더 명확하게 식별하게 하기 위함입니다/
- 반응형 사이징을 적용하여 모바일 사이즈에서도 사용이 가능하도록 하였습니다.
- 쿼리파라미터를 통해 강의 목록을 관리하고있기때문에 화면 새로고침시에도 데이터를 유지시킬 수 있고, 링크 공유를 통해 시간표를 공유할 수 있도록 했습니다.
- 이러닝, 교외수업 등과 같은 특수한 요소에 대해서는 별개의 테이블로 분리하였고, 해당 섹션에서 확인할 수 있습니다.

## ETC

- 세로 사이즈가 너무 작을 경우 `modal` 스페이스가 잘리는 문제가 있는데, 해당 문제 수정중입니다.
- 강의 목록 테이블에 존재하는 강의 목록 요소가 `auto` 처리가 되어있어 해당부분 고정 사이즈로 사용할 수 있도록 수정중입니다.
- 백엔드 api 응답사양 업데이트가 되면 타임테이블에 있는 총 학점 목록까지 보여줄 예정입니다.

## Screenshot

<img width="1441" alt="image" src="https://github.com/user-attachments/assets/6b874a17-219e-47ae-bde0-e91c15e45c33">

2024-08-29 10:32 UTC, gwansikk requested changes

2024-08-29 10:32 UTC, gwansikk commented on apps/time/package.json
> +    "@suspensive/react": "^2.14.0",
👍👍👍👍👍👍👍

2024-08-29 10:32 UTC, gwansikk commented on apps/time/src/widgets/time-table/model/hooks/useLectureByParams.ts
> +    enabled: !!idList.length,
```suggestion
  const { data, isError } = useQuery({
    queryKey: timeTableQueryKeys.getLectureByParams(idList),
    queryFn: () => getLectureByParams(idList)
    enabled: !!idList.length,
```
'enabled'로 이미 있을 경우 해당 쿼리가 실행되도록 되어 있어요, 'null'을 사용해야 하는 케이스가 있나요??

2024-08-29 10:32 UTC, gwansikk commented on apps/time/src/widgets/time-table/ui/TimeTableUtilButtons.tsx
> +      }, 2000);
setTimeout이 수행되기 전에 컴포넌트가 언마운트 된다면, 클린업이 없어 메모리 누수가 발생될 수 있다고 생각해요

2024-08-29 11:14 UTC, SWARVY commented on apps/time/src/widgets/time-table/model/hooks/useLectureByParams.ts
> +    enabled: !!idList.length,
어 그렇네요 `enabled`가 이미 되어있어서 해당 케이스가 필요하지 않겠네요!

2024-08-30 14:12 UTC, Jeong-Ag requested changes
수고 많으셨습니다!!👏👏

2024-08-30 14:12 UTC, Jeong-Ag commented on apps/time/src/widgets/time-table/ui/TimeTable.tsx
> +            {...SPECIAL_LECTURE_TABLE_HEADER.map((header) => (
`스프레드 연산자`를 사용해서 `...SPECIAL_LECTURE_TABLE_HEADER`로 작성하신 이유가 있으실까요? `SPECIAL_LECTURE_TABLE_HEADER`으로 해도 괜찮을 것 같은데 궁금해서 여쭤봅니다!

2024-08-31 12:43 UTC, SWARVY commented on apps/time/src/widgets/time-table/ui/TimeTable.tsx
> +            {...SPECIAL_LECTURE_TABLE_HEADER.map((header) => (
이부분은 제가 별 생각 없이 스프레드 연산자를 적용한 것 같아서 변경하도록 하겠습니다~

2024-08-31 12:59 UTC, gwansikk approved these changes

2024-08-31 12:59 UTC, gwansikk commented on apps/time/src/widgets/time-table/ui/TimeTableUtilButtons.tsx
> +  };
컴포넌트가 언마운트되어도 setTimeout이 실행될 수 있어요. `useEffect`를 이용하여 `setTimeout`을 클린업 하는 건 어떨까요

```ts
useEffect(() => {
  return () => {
    // 컴포넌트가 언마운트될 때 타이머를 클리어
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
    }
  };
}, []);
```

2024-08-31 12:59 UTC, gwansikk commented on apps/time/src/widgets/time-table/ui/TimeTableUtilButtons.tsx
> +  };
개선 후 머지가 가능한 생태이므로 머지 부탁드려요. 승인합니다

2024-08-31 13:06 UTC, Jeong-Ag approved these changes

2024-08-31 13:18 UTC, merged