refactor(member): 활동 2차 QA 피드백 반영 수정 2
kgu-clab/clab-platforms pull request #233
Opened 2024-09-12 12:34 UTC by Jeong-Ag

## Summary

> #229

운영진 대상으로 진행된 2차 활동 QA를 바탕으로 코드를 개선합니다.

## Tasks

- `board` 타입 별 파일 업로드
- 글자수 제한 로직 추가 및 글자수 확인 컴포넌트 생성
- 공지사항 제목 및 파일 조회 가능하도록 수정
- 활동 그룹 멤버가 아닐 경우 과제 및 주차별 활동 파일 접근 제한
- 과제 목록에서 과제 제출 마감기한 확인
- 활동 지원 멤버 일괄 승인 기능 추가
- 상태 변경 시 확인 `modal` 추가
- `play` ->`members` 도메인 변경에 따른 url 수정
- 마이페이지 나의 활동에 `pagination` 추가

## ETC

백엔드 수정사항 작업 완료되면 3차 QA 진행하겠습니다 :)

## Screenshot

<img width="975" alt="스크린샷 2024-09-12 오후 9 21 13" src="https://github.com/user-attachments/assets/4afab45c-340a-49e9-a18a-a2b345201de9">
<img width="932" alt="스크린샷 2024-09-12 오후 9 22 28" src="https://github.com/user-attachments/assets/72056e9f-3872-44a2-9dbf-5d7089b9dc98">
<img width="917" alt="스크린샷 2024-09-12 오후 9 23 10" src="https://github.com/user-attachments/assets/9768a8ee-90d4-42e3-b737-bcd968a09136">
<img width="930" alt="스크린샷 2024-09-12 오후 9 22 04" src="https://github.com/user-attachments/assets/e7cd9122-b737-415a-83a6-52156eaa5013">
<img width="567" alt="스크린샷 2024-09-12 오후 9 29 02" src="https://github.com/user-attachments/assets/5f4181e1-bf23-4b38-98c0-e5aa136d69d4">
<img width="958" alt="스크린샷 2024-09-12 오후 9 21 30" src="https://github.com/user-attachments/assets/fcec10e0-3df6-4544-ad5e-9eaa8e337872">
<img width="913" alt="스크린샷 2024-09-12 오후 9 21 22" src="https://github.com/user-attachments/assets/3b34b711-0c90-4a80-b3a2-c0256ed6d0c5">

2024-09-12 16:25 UTC, SWARVY approved these changes
크게 수정요청 드릴 부분이 없는 것 같아요! 몇가지 리뷰 남겨드렸으니 한번 확인해주세요
어프롭 하겠습니다~

![image](https://github.com/user-attachments/assets/a0b27fe6-311f-4f3c-ade4-7a881464a9bd)

요거 사진보고 느낀건데, 이거 사진 중앙정렬 시키는게 더 깔끔해보일거같아요

2024-09-12 16:25 UTC, SWARVY commented on apps/member/src/api/activity.ts
> +  memberId: Array<string>;
`Array<string>`과 `string[]`은 서로 동일한 타입을 나타내는걸 알고계실거라고 생각해요.
팀 컨벤션 차원에서 앞으로 어떤 방식을 사용하여 `array` 타입을 나타낼지에 대해서 이야기해보면 좋을 것 같아요 🤔

2024-09-12 16:25 UTC, SWARVY commented on apps/member/src/components/common/File/File.tsx
> +
저번에 리뷰 남긴 개행으로 문맥을 구분하는 과정을 추가해주셨네요~ 좋습니다 👏

2024-09-12 16:25 UTC, SWARVY commented on apps/member/src/components/modal/CheckConfirmModal/CheckConfirmModal.tsx
> +        <Button className="w-full" color="red" onClick={() => handleClose()}>
인자가 필요한게 아니라면 굳이 화살함수로 표기할 필요는 없어보여요

```suggestion
        <Button className="w-full" color="red" onClick={handleClose}>
```

2024-09-12 16:25 UTC, SWARVY commented on apps/member/src/components/group/ActivityNoticeSection/ActivityNoticeSection.tsx
> +import ActivityNoticeModal from '@components/modal/ActivityNoticeModal/ActivityNoticeModal';
저번에 폴더 구조를 말씀드리면서 생각했던 문제지만, 현행 `import` 형태는 불필요하게 복잡한 구조를 가지고 있다고 생각해요
지금도 해당 경로를 자세히 살펴보면

`@components/modal/ActivityNoticeModal/ActivityNoticeModal` < 뒤쪽에 적힌 `ActivityNoticeModal`이 두번 반복 / 그 때문에 불필요하게 `import` 경로가 길어지고 있어요.

해당 요소에서만 사용하는 컴포넌트들이 있을 수 있기때문에 디렉토링을 해 놓았다고 생각하기에, 해당 디렉토리에는 `index.ts`를 생성하여 `export`를 관리하는 `배럴` 패턴을 적용한다면 `import`문의 의미를 잃지 않으면서도 간략하게 나타낼 수 있을 것 같아요

2024-09-12 16:34 UTC, gwansikk requested changes

2024-09-12 16:34 UTC, gwansikk commented on apps/member/src/components/group/WeeklyActivitySection/WeeklyActivitySection.tsx
> +          [...data].map((activity, index) => (
```suggestion
          data.map((activity, index) => (
```
 새 배열로 만든 이유가 있나요??

2024-09-13 01:44 UTC, Jeong-Ag commented on apps/member/src/api/activity.ts
> +  memberId: Array<string>;
저는 `Array<string>`이 명확하게 `array`라는 것을 명시해줘서 타입으로 더 적절하다고 생각하는데 다들 어떻게 생각하실지 궁금해요! 
@gwansikk @SWARVY

2024-09-13 01:48 UTC, Jeong-Ag commented on apps/member/src/components/group/ActivityNoticeSection/ActivityNoticeSection.tsx
> +import ActivityNoticeModal from '@components/modal/ActivityNoticeModal/ActivityNoticeModal';
여러 곳에서 사용되는 `modal`은 `modal` 디렉토리 내에 위치시켜 `index.ts` 파일로 관리하고, 특정 요소 내에서만 사용 되는 경우는 해당 폴더 내에 위치시키는 걸로 변경할게요 :)

2024-09-13 01:49 UTC, Jeong-Ag commented on apps/member/src/components/group/WeeklyActivitySection/WeeklyActivitySection.tsx
> +          [...data].map((activity, index) => (
데이터 정렬 때문에 작성 됐던 코드가 남아있었네요🥲 수정하겠습니다!

2024-09-13 02:19 UTC, Jeong-Ag commented on apps/member/src/components/modal/CheckConfirmModal/CheckConfirmModal.tsx
> +        <Button className="w-full" color="red" onClick={() => handleClose()}>
헉 코드 변경할 때 수정이 안 됐나봐요 알려주셔서 감사해요 :)

2024-09-13 02:22 UTC, Jeong-Ag commented
> 크게 수정요청 드릴 부분이 없는 것 같아요! 몇가지 리뷰 남겨드렸으니 한번 확인해주세요 어프롭 하겠습니다~ 수고하셨어요!
> 
> + 추가로 별건 아닌데 요 컴포넌트 사진 중앙정렬 시키는게 더 깔끔해보일거같아요
> 
> ![image](https://private-user-images.githubusercontent.com/53262430/366972877-a0b27fe6-311f-4f3c-ade4-7a881464a9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTI0NjQsIm5iZiI6MTcyNjE5MjE2NCwicGF0aCI6Ii81MzI2MjQzMC8zNjY5NzI4NzctYTBiMjdmZTYtMzExZi00ZjNjLWFkZTQtN2E4ODE0NjRhOWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAxNDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OWRhMjY5OGRiMmZkMDYwNmU3MTFjOWY3ODViMWNiZmY0MGZiNTJkNzdlNDBiZjQ5MmNlNDcxNDczZmQzNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jCmzOG-g9nju61DbtBVKz0wQIG6K1I3bgkUnmESFatQ)

`margin`을 조정하여 중앙에 오도록 하였습니다!! 더 깔끔해 보이네요 👀

<img width="527" alt="스크린샷 2024-09-13 오전 11 17 15" src="https://github.com/user-attachments/assets/f6bb5e79-2d43-4550-8927-e42e1392ded8">

2024-09-13 02:38 UTC, gwansikk approved these changes
LGTM👍👍

2024-09-13 02:39 UTC, merged