feat(land): migration landing page and create first section
kgu-clab/clab-platforms pull request #257
Opened 2024-11-23 10:58 UTC by Jeong-Ag

## Summary

> #181 

랜딩 페이지를 `next.js`로 마이그레이션 하고 메인 페이지의 첫 번째 뷰를 생성합니다.

## Tasks

- `next.js 15`로 upgrade
- 레이아웃 설정
- 메인 페이지 내 첫 번째 뷰 생성
- 기본 폰트 및 디렉토리 설정

## To Reviewer

next.js에 익숙하지 않아 실수가 많을 수 있어요 ........ 🥲 따끔한 충고 부탁드려요

## Screenshot

<img width="1792" alt="스크린샷 2024-11-23 오후 3 25 07" src="https://github.com/user-attachments/assets/ff027b96-4ccf-4f6e-b7b0-b11354a23f3c">
<img width="1792" alt="스크린샷 2024-11-23 오후 3 25 10" src="https://github.com/user-attachments/assets/a2a926d9-cb8f-46cf-bb00-7e17a8488218">
<img width="672" alt="스크린샷 2024-11-23 오후 7 28 48" src="https://github.com/user-attachments/assets/af4b1003-004a-44d8-8bd4-d0e5f7863cb6">

2024-11-23 16:39 UTC, SWARVY requested changes
수고 많으셨어요 :) 아래 리뷰 검토 부탁드립니다

2024-11-23 16:39 UTC, SWARVY commented on apps/land/src/components/Nav.tsx
> +          </Button>
의도는 이해하지만 Button의 onClick으로 새 창을 여는 행위는 결국 a태그의 기능과 동일해지는 것 같은데, 어떻게 생각하시나요?

2024-11-24 04:13 UTC, Jeong-Ag commented on apps/land/src/components/Footer.tsx
> +      <a href={INFORMATION_URL.GITHUB} target="_blank">
GitHub URL이 외부 링크라서 `next/link`의 이점이 적용되지 않을 것 같아 `a` 태그를 사용했어요. 이런 경우엔 `a` 태그가 더 직관적이지 않을까 했는데 일관성 있게 `next/link`를 사용하는 것이 더 좋을까요?

2024-11-24 04:15 UTC, Jeong-Ag commented on apps/land/src/components/Nav.tsx
> +          </Button>
요소의 의미를 명확하게 하기 위해 `Button`을 사용했는데 기능이 새 창을 여는 동작이니까 불필요하게 `Button`을 사용하는 것 보단 `a` 태그를 통해 이동시키는 것이 적합할 것 같네요! 수정하도록 하겠습니다 :)

2024-11-24 04:22 UTC, Jeong-Ag commented on apps/land/src/components/Nav.tsx
> +import { useEffect, useRef, useState } from 'react';
엇 무사히 동작해서 넣었다가 없앴는데... use client 사용해서 명확하게 하는게 좋을 것 같네요
추후에 오류 발생할 수도 있으니 추가하겠습니다!

2024-11-24 04:31 UTC, Jeong-Ag commented on apps/land/src/app/home/page.tsx
> +'use client';
`next/link`를 사용하여 페이지를 이동시키면 클라이언트 컴포넌트가 필요하지 않겠네요. 성능면에서 생각하지 못했는데 알려주셔서 감사해요
`useRouter` 사용하지 않고 `next/link`를 사용하도록 수정하겠습니다!

2024-11-24 04:35 UTC, Jeong-Ag commented on apps/land/src/app/home/components/TextSlider.tsx
> +          </h1>
헉 좋은 내용 감사합니다!! 알려주신 내용을 보니 SEO와 접근성 측면에서 `h1` 태그가 부적합하다는 점이 잘 이해됐어요. 다른 태그 사용하도록 하겠습니다 ☺️

2024-11-24 08:43 UTC, SWARVY approved these changes

2024-11-24 08:44 UTC, SWARVY commented
LGTM. 수고하셨습니다 :)

2024-11-26 10:11 UTC, merged